# This is a basic workflow to help you get started with Actions

name: Android build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        arch: [ "arm64-v8a" ]
      fail-fast: false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      # Runs a set of commands using the runners shell
      - name: "Build shaderc for Android ${{matrix.arch}}"
        run: |
          pushd ..
          export ANDROID_NDK_HOME=${{env.ANDROID_NDK_LATEST_HOME}}
          popd
          
          ./utils/git-sync-deps
          # Workaround a cmake bug
          sed -i'' -e 's/android log/android -llog/g' third_party/spirv-tools/source/CMakeLists.txt
          cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DANDROID_PLATFORM=26 -DANDROID_ABI=${{matrix.arch}} -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DSHADERC_SKIP_TESTS=1
          cmake --build build --clean-first -- -j8
          cd build/libshaderc
          cp libshaderc_shared.so libshaderc.so
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip libshaderc.so
          # | echo "Build exit code: $?"
          # --verbose

      - name: Upload libshaderc
        uses: actions/upload-artifact@main
        with:
          name: libshaderc-${{matrix.arch}}
          path: build/libshaderc/libshaderc.so

      - name: Upload libshaderc (with debug info)
        uses: actions/upload-artifact@main
        with:
          name: libshaderc-${{matrix.arch}}-debug
          path: build/libshaderc/libshaderc_shared.so
  aar:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Get packaging script
      uses: actions/checkout@main
      with:
        repository: 'MojoLauncher/mesaunified-packager'
    - name: Get shaderc arm64
      uses: actions/download-artifact@main
      with:
        name: libshaderc-arm64-v8a
        path: shaderc/arm64-v8a
    - name: Get shaderc armv7
      uses: actions/download-artifact@main
      with:
        name: libshaderc-armeabi-v7a
        path: shaderc/armeabi-v7a
    - name: Get shaderc x86
      uses: actions/download-artifact@main
      with:
        name: libshaderc-x86
        path: shaderc/x86
    - name: Get shaderc x86_64
      uses: actions/download-artifact@main
      with:
        name: libshaderc-x86_64
        path: shaderc/x86_64
    - name: Pack AAR
      run: bash create_aar.sh $GITHUB_WORKSPACE/shaderc shaderc
    - name: Upload packaging result
      uses: actions/upload-artifact@main
      with:
        name: shaderc-aar
        path: shaderc.aar
